# version: '3.2'

# services:    
#  postgres:
#     image: postgres:12.17-alpine3.18
#     container_name: todos_database
#     ports:
#       - 5433:5433
#     environment:
#       - POSTGRES_USER:postgres
#       - POSTGRES_PASSWORD:root
#       - POSTGRES_DB:todos
#     volumes:
#     - Todos:/var/lib/postgresql/data 
     
#  backend:
#     build: .
#     container_name: todos_Backend
#     ports: 
#       - 9090:9090
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/todos
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: root
#     depends_on:
#      - postgres
      
    

# volumes:
#   Todos:
  
version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: dockerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:9090"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: dockerpassword

volumes:
  postgres-data: